###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "id": "15236454",
    "name": "Ernesto",
    "username": "ernesto",
    "email": "alop@mail.com",
    "clave": "clave",
    "tipo": "Vendedor"
}

###
GET http://localhost:9000/api/users HTTP/1.1

###
POST http://localhost:9000/api/ventas HTTP/1.1
Content-Type: application/json


{
    "idVenta": "22222",
    "descripcion": "Zpatos Color Rozo",
    "idCliente": "01245",
    "cliente": "ernesto",
    "fecha": "26/07/2021",
    "estado": "cacelada"    
}

###
GET http://localhost:9000/api/ventas HTTP/1.1

###
DELETE http://localhost:9000/api/ventas/616cc701db8df7868b402cb6 HTTP/1.1

###
PUT http://localhost:9000/api/ventas/616cc470db8df7868b402cac HTTP/1.1

{
    "idVenta": "22222",
    "descripcion": "Blusas Color Rojo",
    "idCliente": "01245",
    "cliente": "ernesto",
    "fecha": "26/07/2021",
    "estado": "estado"    
}